-- ========================================================
-- SEKAOS PROJECT - SUPABASE DATABASE SCHEMA & POLICIES
-- ========================================================
-- Jalankan skrip SQL ini di Supabase SQL Editor untuk membuat
-- tabel, relasi, RLS policies, dan sample data produk.
-- ========================================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. TABEL KATEGORI (categories)
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(100) NOT NULL UNIQUE,
    icon VARCHAR(50) DEFAULT 'fas fa-tshirt',
    sort_order INT DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. TABEL PRODUK (products)
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT REFERENCES public.categories(id) ON DELETE RESTRICT,
    name VARCHAR(200) NOT NULL,
    slug VARCHAR(220) NOT NULL UNIQUE,
    description TEXT,
    material_specs VARCHAR(255),
    min_order VARCHAR(50) DEFAULT '12 pcs',
    price_estimate VARCHAR(100) DEFAULT 'Hubungi CS',
    is_featured BOOLEAN DEFAULT false,
    is_active BOOLEAN DEFAULT true,
    views_count INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. TABEL FOTO PRODUK (product_images)
CREATE TABLE IF NOT EXISTS public.product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    image_url TEXT NOT NULL,
    is_primary BOOLEAN DEFAULT false,
    sort_order INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. TABEL PENGATURAN UMUM (settings)
CREATE TABLE IF NOT EXISTS public.settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key VARCHAR(50) NOT NULL UNIQUE,
    setting_value TEXT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ========================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ========================================================

-- Aktifkan RLS di semua tabel
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

-- Policy Categories:
-- Publik boleh melihat kategori aktif
CREATE POLICY "Public categories read" ON public.categories
    FOR SELECT USING (is_active = true);

-- Admin (authenticated) memiliki akses penuh
CREATE POLICY "Admin categories all" ON public.categories
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Policy Products:
-- Publik boleh melihat produk aktif
CREATE POLICY "Public products read" ON public.products
    FOR SELECT USING (is_active = true);

-- Admin (authenticated) memiliki akses penuh
CREATE POLICY "Admin products all" ON public.products
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Policy Product Images:
-- Publik boleh melihat foto produk
CREATE POLICY "Public product_images read" ON public.product_images
    FOR SELECT USING (true);

-- Admin (authenticated) memiliki akses penuh
CREATE POLICY "Admin product_images all" ON public.product_images
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Policy Settings:
-- Publik boleh membaca pengaturan web
CREATE POLICY "Public settings read" ON public.settings
    FOR SELECT USING (true);

-- Admin (authenticated) boleh mengubah pengaturan web
CREATE POLICY "Admin settings all" ON public.settings
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ========================================================
-- STORAGE BUCKET SETUP (product-images)
-- ========================================================
-- Jalankan di SQL Editor untuk membuat storage bucket
INSERT INTO storage.buckets (id, name, public)
VALUES ('product-images', 'product-images', true)
ON CONFLICT (id) DO NOTHING;

-- Policy Storage: Siapapun bisa melihat gambar
CREATE POLICY "Public Access Storage" ON storage.objects
    FOR SELECT USING (bucket_id = 'product-images');

-- Policy Storage: Hanya Admin Authenticated yang bisa upload/edit/hapus gambar
CREATE POLICY "Admin Upload Storage" ON storage.objects
    FOR INSERT TO authenticated WITH CHECK (bucket_id = 'product-images');

CREATE POLICY "Admin Update Storage" ON storage.objects
    FOR UPDATE TO authenticated USING (bucket_id = 'product-images');

CREATE POLICY "Admin Delete Storage" ON storage.objects
    FOR DELETE TO authenticated USING (bucket_id = 'product-images');

-- ========================================================
-- DATA AWAL / SEED DATA
-- ========================================================

-- Seed Settings
INSERT INTO public.settings (setting_key, setting_value) VALUES
('whatsapp_number', '6289671830693'),
('whatsapp_template', 'Halo Admin Sekaos Project, saya tertarik dengan produk {product_name}. Bisa konsultasi bahan dan harganya?'),
('instagram_url', 'https://instagram.com/sekaos.project'),
('instagram_handle', '@sekaos.project'),
('address', 'Semarang, Jawa Tengah'),
('maps_url', 'https://maps.app.goo.gl/SPYvU4N9ifpcvq6f9')
ON CONFLICT (setting_key) DO NOTHING;

-- Seed Categories
INSERT INTO public.categories (id, name, slug, icon, sort_order) VALUES
(1, 'Rompi / Vest', 'rompi-vest', 'fas fa-vest', 1),
(2, 'PDH & Kemeja', 'pdh-kemeja', 'fas fa-user-tie', 2),
(3, 'Kaos Custom', 'kaos-custom', 'fas fa-tshirt', 3),
(4, 'Jersey Custom', 'jersey-custom', 'fas fa-running', 4),
(5, 'Seragam & Wearpack', 'seragam-wearpack', 'fas fa-user-friends', 5),
(6, 'Merchandise & Aksesoris', 'merchandise-aksesoris', 'fas fa-medal', 6)
ON CONFLICT (id) DO NOTHING;

-- Reset sequence id category
SELECT setval('public.categories_id_seq', (SELECT MAX(id) FROM public.categories));

-- Seed Products
INSERT INTO public.products (category_id, name, slug, description, material_specs, min_order, price_estimate, is_featured, is_active) VALUES
(1, 'Rompi Tactical Lapangan 4 Saku', 'rompi-tactical-lapangan-4-saku', 'Rompi lapangan multifungsi dengan bahan Ripstop atau Taslan tahan angin dan cipratan air. Dilengkapi 4 saku fungsional, furing jaring adem, dan bordir komputer rapi.', 'Bahan Ripstop / Taslan + Furing Jala', '12 pcs', 'Hubungi CS', true, true),
(2, 'Kemeja PDH Organisasi Nagata Drill', 'kemeja-pdh-organisasi-nagata-drill', 'Kemeja PDH/PDL resmi untuk organisasi mahasiswa, komunitas, atau instansi. Menggunakan kain Nagata Drill original yang halus, tebal, dan tidak panas.', 'Nagata Drill Original', '12 pcs', 'Hubungi CS', true, true),
(3, 'Kaos Event Gathering Cotton Combed 24s', 'kaos-event-gathering-cotton-combed-24s', 'Kaos event premium dengan bahan 100% Cotton Combed 24s anti-bakteri. Opsi sablon variatif: DTF Full Color, Plastisol, atau Rubber berkualitas tahan cuci.', 'Cotton Combed 24s Premium', '24 pcs', 'Hubungi CS', true, true),
(4, 'Jersey Futsal / Olahraga Dryfit Printing', 'jersey-futsal-olahraga-dryfit-printing', 'Jersey olahraga full printing sublimasi tajam tidak luntur. Menggunakan bahan Dryfit Milano / Brazil yang cepat kering dan berpori untuk sirkulasi udara maksimal.', 'Dryfit Milano / Brazil Sublim', '12 pcs', 'Hubungi CS', true, true),
(5, 'Seragam Kerja Lapangan Wearpack Safety', 'seragam-kerja-lapangan-wearpack-safety', 'Wearpack / seragam safety dua potong atau terusan dengan scotlight reflektor menyala saat gelap. Jahitan rantai 3 jarum sangat kuat untuk aktivitas lapangan.', 'American Drill / Japan Drill + Scotlight 3M', '12 pcs', 'Hubungi CS', true, true),
(6, 'Paket ID Card + Tali Lanyard Custom', 'paket-id-card-tali-lanyard-custom', 'Paket identitas panitia dan peserta event: Card PVC tahan air dan lanyard printing 2 cm kait besi tebal dengan stopper.', 'PVC Card 0.76mm + Tissue Lanyard', '30 pcs', 'Hubungi CS', true, true);
